name: Create Azure Web App

on:
  workflow_dispatch:

jobs:
  create-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure using the service principal credentials stored in GitHub Secretse
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
