name: Create Azure Web App

on:
  workflow_dispatch:

jobs:
  create-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure using the service principal credentials stored in GitHub Secretse
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # Create the Resource Group if it doesn't exist
      - name: 'Create Azure Resource Group'
        run: |
          az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}

      # Create the Web App Service Plan (if it doesn't exist)
      - name: 'Create Azure App Service Plan'
        run: |
          az appservice plan create --name "${{ secrets.AZURE_APPSERVICE_PLAN }}" \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --location ${{ secrets.AZURE_LOCATION }} \
          --sku F1

      # Create the Azure Web App (if it doesn't exist)
      - name: 'Create Azure Web App'
        run: |
          az webapp create --name ${{ secrets.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --plan "${{ secrets.AZURE_APPSERVICE_PLAN }}" \
          --runtime "${{ secrets.AZURE_WEBAPP_RUNTIME }}"
