name: Deploy .NET 8 Web App to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ secrets.AZURE_DOTNET_VERSION }}

    - name: Set environment variables for appsettings.json substitution
      env:
        Auth0__Audience: ${{ secrets.AUTH0_AUDIENCE }}
        Auth0__ClientId: ${{ secrets.AUTH0_CLIENT_ID }}
        Auth0__ClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}
        Auth0__Domain: ${{ secrets.AUTH0_DOMAIN }}
        Auth0__ManagementScopes: ${{ secrets.AUTH0_MANAGEMENT_SCOPES }}
        Auth0__Roles__Establishment: ${{ secrets.AUTH0_ROLES_ESTABLISHMENT }}
        Auth0__Roles__User: ${{ secrets.AUTH0_ROLES_USER }}
        Auth0__Roles__Admin: ${{ secrets.AUTH0_ROLES_ADMIN }}
        Mapbox__AccessToken: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        run: echo "Environment variables set for appsettings.json substitution"

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace }}/nowaround.api/appsettings.json'

    - name: Set up dependency caching for faster builds
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --verbosity normal

    - name: Publish the app
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ${{ github.workspace }}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ github.workspace }}/publish
