name: Deploy .NET 8 Web App to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ secrets.AZURE_DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the app
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity diagnostic

    - name: Publish the app
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: ${{ github.workspace }}/publish
